name: KoukeNeko-CommandGUI
version: '1.0-SNAPSHOT'
main: dev.doeshing.koukeNekoCommandGUI.KoukeNekoCommandGUI
api-version: '1.21'

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: true